version: "3.7"
services:
  faveplace_backend:
    image: faveplace/faveplace:latest
    #build: .
    container_name: faveplace_backend
    ports:
      - ${PRIVATE_IP}:8080:8080
    env_file:
      - ./.env
    environment:
      - NODE_ENV=production
    networks:
      - faveplace

networks:
  faveplace:
