name: Build and Deploy Stage

on:
  push:
    branches:
      - 'master'
  repository_dispatch:
    types: trigger-deploy

jobs:
  deploy-hetzner-stage:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: copy files via ssh
        uses: appleboy/scp-action@master
        with:
          source: "./**"
          target: fav-place-taxi
          host: ${{ secrets.HCLOUD_HOST }}
          username: ${{ secrets.HCLOUD_SSH_USER }}
          key: ${{ secrets.HCLOUD_SSH_PRIVATE_KEY }}
          rm: true

      - name: executing remote ssh commands - system setup
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HCLOUD_HOST }}
          username: ${{ secrets.HCLOUD_SSH_USER }}
          key: ${{ secrets.HCLOUD_SSH_PRIVATE_KEY }}
          script: |
            sysctl -w vm.max_map_count=262144
            apt update && apt --yes upgrade

      - name: executing remote ssh commands - setting .env
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HCLOUD_HOST }}
          username: ${{ secrets.HCLOUD_SSH_USER }}
          passphrase: ${{ secrets.HCLOUD_SSH_PASSPHRASE }}
          key: ${{ secrets.HCLOUD_SSH_PRIVATE_KEY }}
          script: |
            cd fav-place-taxi
            rm -f .env && touch .env
            echo "PRIVATE_IP=10.0.0.6" >> .env
            cd client
            rm -f .env && touch .env
            echo "PUBLIC_URL=https://fav-place-taxi.peerigon.com" >> .env
            echo "REACT_APP_MAPBOX_ACCESS_TOKEN=pk.eyJ1IjoibWFydGluZ2Fzc25lciIsImEiOiJjazgxbXVpcmYwY2g5M29td3c0cTdleXU4In0.luUjtUyLz_gDnfnx_X7g3g" >> .env
            echo "REACT_APP_FIREBASE_API_KEY=AIzaSyBEz6m8XjVVhx3G54ntUq74sHH06HUzZpM" >> .env
            echo "REACT_APP_FIREBASE_AUTH_DOMAIN=favorite-place-taxi.firebaseapp.com" >> .env
            echo "REACT_APP_FIREBASE_DATABASE_URL=https://favorite-place-taxi.firebaseio.com" >> .env
            echo "REACT_APP_FIREBASE_PROJECT_ID=favorite-place-taxi" >> .env
            echo "REACT_APP_FIREBASE_STORAGE_BUCKET=favorite-place-taxi.appspot.com" >> .env
            echo "REACT_APP_FIREBASE_MESSAGING_SENDER_ID=520966478997" >> .env
            echo "REACT_APP_FIREBASE_APP_ID=1:520966478997:web:97fd549437d184b1ec0f9c" >> .env

      - name: executing remote ssh commands - docker-compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HCLOUD_HOST }}
          username: ${{ secrets.HCLOUD_SSH_USER }}
          passphrase: ${{ secrets.HCLOUD_SSH_PASSPHRASE }}
          key: ${{ secrets.HCLOUD_SSH_PRIVATE_KEY }}
          script: |
            cd fav-place-taxi
            docker-compose -f docker-compose.yml pull
            docker-compose -f docker-compose.yml build
            docker-compose -f docker-compose.yml down
            docker-compose -f docker-compose.yml up -d
